# Base Keycloak image
FROM quay.io/keycloak/keycloak:25.0.5

# Set environment variable to use PostgreSQL as the database
ENV KC_DB=postgres

WORKDIR /opt/keycloak

# Build Keycloak with PostgreSQL as the database configuration
RUN /opt/keycloak/bin/kc.sh build

# Entry point to run Keycloak
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]